trigger:
  branches:
    include: 
    - develop
    - master
  paths:
    include: 
     - /src/*

resources:
  repositories:
  - repository: devops
    type: git
    name: pub/devops
    ref: master


jobs:
- template: dotnet-build-deploy.yml@devops
  parameters:
    projectName: 'Code2.Tools.Csv.Repos'	#main project name, default: null
#    testProjects: '**/*Tests.csproj'	#test projects filter pattern, default: '**/*Tests.csproj'
    createNugetPackage: true		#create a nuget package, default: false
    gitReleaseBranchName: 'master'	#git branch name to trigger creation of git tag and release, default: ''
#    buildConfiguration: 'Release'	#build configuration, default: 'Release'